export const PRODUCT_TYPES = {
	GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
	GET_ONE_PRODUCT: 'GET_ONE_PRODUCT',
	ADD_PRODUCT: 'ADD_PRODUCT',
	UPDATE_PRODUCT: 'UPDATE_PRODUCT',
	DELETE_PRODUCT: 'DELETE_PRODUCT',
	GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
	ADD_CATEGORY: 'ADD_CATEGORY',
	UPDATE_CATEGORY: 'UPDATE_CATEGORY',
	DELETE_CATEGORY: 'DELETE_CATEGORY',
};
