export const PRODUCT_TYPES = {
	GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
	GET_ONE_PRODUCT: 'GET_ONE_PRODUCT',
	ADD_PRODUCT: 'ADD_PRODUCT',
	UPDATE_PRODUCT: 'UPDATE_PRODUCT',
	DELETE_PRODUCT: 'DELETE_PRODUCT',
};
