export const GLOBAL_TYPES = {
	TOGGLE_MENU: 'TOGGLE_MENU',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	SET_DATA_TO_EDIT: 'SET_DATA_TO_EDIT',
	CLEAN_DATA_TO_EDIT: 'CLEAN_DATA_TO_EDIT',
};
